image: mcr.microsoft.com/playwright:v1.45.0-jammy

options:
  max-time: 30

pipelines:
  default:
    - step:
        name: Test (Playwright)
        caches:
          - node
        script:
          - npm ci
          - npx playwright install --with-deps
          - set -euo pipefail
          - npx playwright test 2>&1 | tee test-console.log
        artifacts:
          - test-console.log
          - allure-results/**

    - step:
        name: Generate & Publish Allure report
        deployment: production
        script:
          - set -euo pipefail
          - test -d allure-results || { echo "allure-results/ not found"; exit 1; }
          - npm i -g allure-commandline --no-audit --no-fund --no-update-notifier
          - allure generate allure-results --clean -o allure-report
          - tmpdir="$(mktemp -d)"
          - cp -r allure-report/* "$tmpdir"/
          - cd "$tmpdir"
          - git init
          - git add .
          - git -c user.name="Bitbucket CI" -c user.email="ci@bitbucket.org" commit -m "Allure for ${BITBUCKET_REPO_FULL_NAME}@${BITBUCKET_COMMIT}"
          - git branch -M main
          - git remote add origin "https://${WEBSITE_USER}:${WEBSITE_APP_PASSWORD}@bitbucket.org/${WEBSITE_REPO}.git"
          - git push -f origin main
          - echo "Published: https://${WEBSITE_REPO}/"
