image: mcr.microsoft.com/playwright:v1.54.0-noble

options:
  max-time: 15

definitions:
  steps:
    - step: &install-and-test
        name: Install deps & run tests
        caches:
          - node
        script:
          - npm ci
          - npx playwright install
          - npm test
        artifacts:
          - allure-results/**

    - step: &generate-allure
        name: Generate Allure report
        image: tobix/allure-cli:2.24.1 
        script:
          - allure generate allure-results --clean -o allure-report
        artifacts:
          - allure-report/**

pipelines:
  default:
    - step: *install-and-test

  branches:
    main:
      - step: *install-and-test
      - step: *generate-allure
    develop:
      - step: *install-and-test
      - step: *generate-allure

  pull-requests:
    "**":
      - step: *install-and-test

  custom:
    smoke-tests:
      - step:
          name: Run smoke subset
          caches:
            - node
          script:
            - npm ci
            - npx playwright install
            - npm run test
          artifacts:
            - allure-results/**
      - step: *generate-allure