image: mcr.microsoft.com/playwright:v1.45.0-jammy

pipelines:
  default:
    - step:
        name: Test + always publish Allure
        caches: [node]
        script:
          - |
            set -euo pipefail
            npm ci
            npx playwright install --with-deps
            # прогон тестов (код выхода может быть != 0 — шаг пометится failed)
            npx playwright test 2>&1 | tee test-console.log
        after-script:
          - |
            set +e
            echo "Generating & publishing Allure report (always)…"
            if [ -d allure-results ]; then
              npm i -g allure-commandline --no-audit --no-fund --no-update-notifier
              allure generate allure-results --clean -o allure-report || true
              tmpdir="$(mktemp -d)"
              cp -r allure-report/* "$tmpdir"/
              cd "$tmpdir"
              git init
              git add .
              GIT_AUTHOR_NAME="Bitbucket CI" GIT_AUTHOR_EMAIL="ci@bitbucket.org" \
              GIT_COMMITTER_NAME="Bitbucket CI" GIT_COMMITTER_EMAIL="ci@bitbucket.org" \
              git commit -m "Allure for ${BITBUCKET_REPO_FULL_NAME}@${BITBUCKET_COMMIT}"
              git branch -M main
              git remote add origin "https://${WEBSITE_USER}:${WEBSITE_APP_PASSWORD}@bitbucket.org/${WEBSITE_REPO}.git"
              git push -f origin main || true
              echo "Published: https://${WEBSITE_REPO}/"
            else
              echo "No allure-results found; nothing to publish."
            fi
        artifacts:
          - test-console.log
          - allure-results/**
