image: mcr.microsoft.com/playwright:v1.45.0-jammy

options:
  max-time: 30

pipelines:
  default:
    - step:
        name: Test (Playwright)
        caches:
          - node
        script:
          - |
            set -euo pipefail
            npm ci
            npx playwright install --with-deps
            npx playwright test 2>&1 | tee test-console.log
        artifacts:
          - test-console.log
          - allure-results/**

    - step:
        name: Generate & Publish Allure report
        deployment: production
        script:
          - |
            set -euo pipefail
            if [ ! -d allure-results ]; then
              echo "allure-results/ not found"; exit 1;
            fi
            npm i -g allure-commandline --no-audit --no-fund --no-update-notifier
            allure generate allure-results --clean -o allure-report
            tmpdir="$(mktemp -d)"
            cp -r allure-report/* "$tmpdir"/
            cd "$tmpdir"
            git init
            git add .
            GIT_AUTHOR_NAME="Bitbucket CI" GIT_AUTHOR_EMAIL="ci@bitbucket.org" \
            GIT_COMMITTER_NAME="Bitbucket CI" GIT_COMMITTER_EMAIL="ci@bitbucket.org" \
            git commit -m "Allure for ${BITBUCKET_REPO_FULL_NAME}@${BITBUCKET_COMMIT}"
            git branch -M main
            git remote add origin "https://${WEBSITE_USER}:${WEBSITE_APP_PASSWORD}@bitbucket.org/${WEBSITE_REPO}.git"
            git push -f origin main
            echo "Published: https://${WEBSITE_REPO}/"
        artifacts:
          - allure-report/**
