name: Mirror to Bitbucket & trigger pipelines
on:
  push:
    branches: [ master ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror all branches (no tags) to Bitbucket
        env:
          BB_USER: ${{ secrets.BITBUCKET_USERNAME }}
          BB_APP_PW: ${{ secrets.BITBUCKET_APP_PASSWORD }}
        run: |
          set -euo pipefail
          git fetch --prune origin '+refs/heads/*:refs/remotes/origin/*'
          AUTH="$(printf '%s:%s' "$BB_USER" "$BB_APP_PW" | base64)"
          URL="https://bitbucket.org/marinanovikova-test/test-automation-framework-nodejs-playwright.git"
          git -c http.extraheader="Authorization: Basic $AUTH" \
          push --prune "$URL" '+refs/remotes/origin/*:refs/heads/*'
