name: Mirror to Bitbucket & trigger pipelines
on:
  push:
    branches: [ master ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to Bitbucket
        run: |
          git push --mirror https://${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_APP_PASSWORD }}@bitbucket.org/marinanovikova-test/test-automation-framework-nodejs-playwright.git
