name: Mirror to Bitbucket & trigger pipelines
on:
  push:
    branches: [ master ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror all branches (no tags) to Bitbucket
        env:
          BB_URL: https://${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_APP_PASSWORD }}@bitbucket.org/marinanovikova-test/test-automation-framework-nodejs-playwright.git
        run: |
          set -euo pipefail
          git --version
          git fetch --prune origin '+refs/heads/*:refs/remotes/origin/*'
          git push --prune "$BB_URL" '+refs/remotes/origin/*:refs/heads/*'
